name: Run Tests

on:
  push:
    branches:
    - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up runtime
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"


    - name: Run tests
#        cd ratelimit 
#        go install
#
#        echo "Running go test in..."
#        pwd
#        ls
#        go test
      run: |
        #!/bin/bash

        echo "Mocking a build number '$RANDOM' and uploading artifact"
        echo $RANDOM > build_number.txt
        cat build_number.txt
        pwd

    - name: Upload build_number artifact
      uses: actions/upload-artifact@v6
      with:
        name: build_number
        path: build_number.txt

  modify_gitops:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download build_number artifact
      uses: actions/download-artifact@v7
      with:
        name: build_number
        path: build_number

    - name: Send pull-request
      run: |
        #!/bin/bash
        echo "github.ref:"
        echo ${{ github.ref }}

        echo "github.ref_name"
        echo ${{ github.ref_name }}

        BUILD_NUMBER=$(cat build_number/build_number.txt)
        REPOSITORY="testcontainers_cicd_gitops"
        CLONE_URL="https://Tbzz83:${{ secrets.GITOPS_PAT }}github.com/Tbzz83/${REPOSITORY}.git"

        echo $BUILD_NUMBER

        git clone $CLONE_URL
        cd $REPOSITORY

        git checkout -b feature_${BUILD_NUMBER}

