name: Run Tests
on:
  push:
    branches:
    - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up runtime
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"


    - name: Run tests
      run: |
        #!/bin/bash
        cd ratelimit 
        go install

        echo "Running go test in..."
        pwd
        ls
        go test

        echo "Mocking a build number '$RANDOM' and uploading artifact"
        echo "v1.${RANDOM}" > build_number.txt
        cat build_number.txt
        pwd

    - name: Upload build_number artifact
      uses: actions/upload-artifact@v6
      with:
        name: build_number
        path: testcontainers_cicd/build_number.txt

  modify_gitops:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build_number artifact
      uses: actions/download-artifact@v7
      with:
        name: build_number
        path: build_number

    - name: Send pull-request
      run: |
        #!/bin/bash
        echo "github.ref:"
        echo ${{ github.ref }}

        echo "github.ref_name"
        echo ${{ github.ref_name }}

        BUILD_NUMBER=$(cat build_number/build_number.txt)
        REPOSITORY="testcontainers_cicd_gitops"
        CLONE_URL="https://${{ secrets.GITOPS_PAT }}@github.com/Tbzz83/${REPOSITORY}.git"
        BRANCH_NAME=feature_${BUILD_NUMBER}

        echo $BUILD_NUMBER

        git clone ${CLONE_URL}
        cd $REPOSITORY

        git checkout -b $BRANCH_NAME
        git status

        echo "Modifying deployment image using sed"
        sed -i "s#^\(\s*- image:\s*\).*#\1testcontainers-cicd:${BUILD_NUMBER}#" manifests/deploy_testcontainers.yaml
        cat manifests/deploy_testcontainers.yaml

        git config --global user.email "cicd@gmail.com"
        git config --global user.name "automate"

        # Commit the changes and push the feature branch to origin
        git add .
        git commit -m "chore: update yaml to $BUILD_NUMBER"
        git push origin $BRANCH_NAME

        # Store the PAT in a file that can be accessed by the
        # GitHub CLI.
        echo "${{ secrets.GITOPS_PAT }}" > token.txt

        # Authorize GitHub CLI for the current repository and
        # create a pull-requests containing the updates.
        gh auth login --with-token < token.txt
        gh pr create \
          --body "" \
          --title "chore: update yaml to $BUILD_NUMBER" \
          --head "$BRANCH_NAME" \
          --base "main"
